all:
	@node ./schemas.js schemas/experiment.json schemas/library.json schemas/replicate.json schemas/functional_characterization_experiment.json schemas/biosample.json schemas/functional_characterization_series.json schemas/replicate.json schemas/genetic_modification.json schemas/reference.json
